server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bandepallis@gmail.com
    password: Saibaba@1999
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: saikalyan
    password: saikalyan
    listener:
      simple:
        auto-startup: true
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notificationservice
    username: root
    password: Kalyan@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

