server:
  port: 8086

spring:
  application:
    name: feed-service
  datasource:
    url: jdbc:mysql://localhost:3306/feedservice
    username: root
    password: Kalyan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
