
spring:
  application:
    name: expense-tracker-service

  datasource:
    url: jdbc:mysql://localhost:3306/tracker
    username: root
    password: Kalyan@123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    log-request-details: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG
    root: INFO
    com.personalexpense.project: DEBUG

  file:
    name: logs/spring-boot-exceptions.log
    # path: logs # Uncomment if you want to specify a log file path

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%"
server:
  port: 8087