server:
  port: 8085

spring:
  application:
    name: follow-service
  datasource:
    url: jdbc:mysql://localhost:3306/followservice
    username: root
    password: Kalyan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
