server:
  port: 8089

jwt:
  secret: mySecretKey
  expiration: 3600000

spring:
  application:
    name: JWT-SERVICE  # Name of the JWT service

  cloud:
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all actuator endpoints (health, info, etc.)
  endpoint:
    health:
      show-details: always  # Shows detailed health information
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
logging:
  level:
    com:
      netflix:
        discovery: DEBUG
    org:
      springframework:
        cloud:
          netflix:
            eureka: DEBUG


