server:
  port: 8089

jwt:
  secret: mySecretKey
  expiration: 3600000

spring:
  application:
    name: jwt-service  # Name of the JWT service

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        discovery: DEBUG
    org:
      springframework:
        cloud:
          netflix:
            eureka: DEBUG
