

server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: Kalyan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


cloud:
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/users/**
      - id: post-service
        uri: lb://post-service
        predicates:
          - Path=/api/posts/**
      - id: comment-reaction-service
        uri: lb://comment-reaction-service
        predicates:
          - Path=/api/comments/**
      - id: notification-service
        uri: lb://notification-service
        predicates:
          - Path=/api/notifications/**
      - id: follow-service
        uri: lb://follow-service
        predicates:
          - Path=/api/follow/**
      - id: feed-service
        uri: lb://feed-service
        predicates:
          - Path=/api/feed/**
      - id: expense-tracker-service
        uri: lb://expense-tracker-service
        predicates:
          - Path=/api/expenses/**




