spring:
  application:
    name: api-gateway
logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.discovery: DEBUG
  config:
    import: "optional:configserver:http://localhost:8888"  # Assuming your Config Server runs on port 8888

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: comment-reaction-service
          uri: lb://comment-reaction-service
          predicates:
            - Path=/api/comments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: follow-service
          uri: lb://follow-service
          predicates:
            - Path=/api/follow/**
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
        - id: expense-tracker-service
          uri: lb://expense-tracker-service
          predicates:
            - Path=/api/expenses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080
