server:
  port: 8088

spring:
  application:
    name: comment-reaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: Kalyan@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
